version: 0.2
env:
  variables:
    S3_BUCKET: "codedeployangular"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build is started on `date`
      - ng build 
  post_build:
     commands:
      - aws s3 cp dist s3://codedeployangular/ --recursive
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
discard-paths: yes
